links = [

    # Uzupełnienie
    "https://bss.ca.pw.edu.pl/Stypendia/Stypendia-z-Funduszu-Stypendialnego/Stypendium-Rektora",
    "https://www.ca.pw.edu.pl/Kwestor/Dzial-Plac/Ubezpieczenia/Ubezpieczenie-NNW",
    "https://ww4.mini.pw.edu.pl/for-students/deans-office/",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/pracownicy/rada/uch_06_2017_07_zal1.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/20250529-iad-plan-studiow-mgr-4sem.pdf",

    # Studia / Dziekanat
    "https://ww2.mini.pw.edu.pl/studia/dziekanat/kontakt-i-dyzury/",
    "https://ww2.mini.pw.edu.pl/studia/dziekanat/informacje-dziekanatu/",
    "https://ww2.mini.pw.edu.pl/studia/dziekanat/dokumenty-i-formularze/",
    "https://ww2.mini.pw.edu.pl/studia/dziekanat/sprawy-socjalne/",
    "https://ww2.mini.pw.edu.pl/studia/dziekanat/dla-dyplomantow-i-promotorow/",

    # Studia / Plany zajęć i procedury
    "https://www.pw.edu.pl/studia/harmonogram-roku-akademickiego",

    # Studia / Inżynierskie i licencjackie
    "https://ww2.mini.pw.edu.pl/studia/inzynierskie-i-licencjackie/rekrutacja/",
    "https://ww2.mini.pw.edu.pl/studia/inzynierskie-i-licencjackie/matematyka-i-analiza-danych/",
    "https://ww2.mini.pw.edu.pl/studia/inzynierskie-i-licencjackie/matematyka-2/",
    "https://ww2.mini.pw.edu.pl/studia/inzynierskie-i-licencjackie/informatyka-2/",
    "https://ww2.mini.pw.edu.pl/studia/inzynierskie-i-licencjackie/computer-science-2/",
    "https://ww2.mini.pw.edu.pl/studia/inzynierskie-i-licencjackie/inzynieria-i-analiza-danych/",
    "https://ww2.mini.pw.edu.pl/studia/inzynierskie-i-licencjackie/rankingi-i-opinie/",
    "https://ww2.mini.pw.edu.pl/studia/inzynierskie-i-licencjackie/wymiana-miedzynarodowa/",
    "https://ww2.mini.pw.edu.pl/studia/inzynierskie-i-licencjackie/praktyki/",

    # Studia / Magisterskie
    "https://ww2.mini.pw.edu.pl/studia/magisterskie/kandydaci/",
    "https://ww2.mini.pw.edu.pl/studia/magisterskie/matematyka-i-analiza-danych/",
    "https://ww2.mini.pw.edu.pl/studia/magisterskie/matematyka/",
    "https://ww2.mini.pw.edu.pl/studia/magisterskie/informatyka/",
    "https://ww2.mini.pw.edu.pl/studia/magisterskie/inzynieria-i-analiza-danych/",
    "https://ww2.mini.pw.edu.pl/studia/magisterskie/rankingi-i-opinie/",

    # Studia / Doktoranci
    "https://ww2.mini.pw.edu.pl/studia/doktoranckie/szkola-doktorska/",

    # Badania / Pracownicy i doktoranci
    "https://ww2.mini.pw.edu.pl/badania/pracownicy-naukowi/",
    "https://ww2.mini.pw.edu.pl/worlds-top-2-scientists/",

    # Badania / Badania naukowe
    "https://ww2.mini.pw.edu.pl/badania/kategorie-dyscyplin-naukowych/",
    "https://ww2.mini.pw.edu.pl/badania/obszary-badawcze/seminaria/",
    "https://ww2.mini.pw.edu.pl/przyznane-granty-dla-pracownikow-wydzialu-mini/",
    "https://ww2.mini.pw.edu.pl/badania/publikacje/wszystkie-publikacje/",

    # Badania / Rada Naukowa Dyscypliny Matematyka
    "https://ww2.mini.pw.edu.pl/badania/rada-naukowa-dyscypliny-matematyka/sklad-rndm/",
    "https://ww2.mini.pw.edu.pl/badania/rada-naukowa-dyscypliny-matematyka/zespoly-rndm/",
    "https://ww2.mini.pw.edu.pl/badania/rada-naukowa-dyscypliny-matematyka/kontakt/",

    # Badania / Rada Naukowa Dyscypliny Informatyka Techniczna i Telekomunikacja
    "https://ww2.mini.pw.edu.pl/badania/rada-naukowa-dyscypliny-informatyka-techniczna-i-telekomunikacja/sklad-rnditit/",
    
    # O Wydziale / Wydział
    "https://ww2.mini.pw.edu.pl/wydzial/o-nas/",
    "https://ww2.mini.pw.edu.pl/wydzial/dziekani/",
    "https://ww2.mini.pw.edu.pl/wydzial/pelnomocnicy-dziekana/",
    "https://ww2.mini.pw.edu.pl/wydzial/jednostki-organizacyjne/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/",
    "https://ww2.mini.pw.edu.pl/wydzial/zamowienia-publiczne/",
    "https://ww2.mini.pw.edu.pl/gmach-wydzialu/wynajem-powierzchni-i-garazu-mini/",
    "https://ww2.mini.pw.edu.pl/studia/plany-zajec-i-procedury/bhp-i-ochrona-przeciwpozarowa/",
    "https://ww2.mini.pw.edu.pl/wydzial/kontakt/",
    
    # O Wydziale / Rada Wydziału i Komisje
    "https://ww2.mini.pw.edu.pl/wydzial/rada-wydzialu/",
    "https://ww2.mini.pw.edu.pl/wydzial/komisje-rady-wydzialu/",
    "https://ww2.mini.pw.edu.pl/wydzial/terminarz-posiedzen-rw/",
    "https://ww2.mini.pw.edu.pl/dla-pracownikow/sprawy-osobowe/komisje-dziekanskie/",
    "https://ww2.mini.pw.edu.pl/wydzial/czlonkowie-senatu/",
    "https://ww2.mini.pw.edu.pl/wydzial/czlonkowie-komisji-uczelnianych/",
    "https://ww2.mini.pw.edu.pl/wydzial/czlonkowie-komisji-wyborczych/",
    
    # O Wydziale / Życie Wydziału
    "https://ww2.mini.pw.edu.pl/zycie-wydzialu/samorzad-studentow/",
    "https://ww2.mini.pw.edu.pl/zycie-wydzialu/kola-naukowe-i-artystyczne/",
    # WYMAGA RĘCZNEGO POBRANIA (BIP PW — cookiewall/blokada scrapowania):
    # "https://www.bip.pw.edu.pl/Sklad-osobowy/Organizacje-spoleczne/Rejestr-uczelnianych-organizacji-studenckich-i-doktoranckich-Politechniki-Warszawskiej/Kolo-Naukowe-Data-Science",
    
    # O Wydziale / Laboratorium
    "https://ww2.mini.pw.edu.pl/laboratorium/oprogramowanie/",
    "https://ww2.mini.pw.edu.pl/laboratorium/laboratoria/",
    "https://ww2.mini.pw.edu.pl/laboratorium/uslugi/",
    "https://ww2.mini.pw.edu.pl/laboratorium/",
    
    # Ważne dokumenty i inne ukryte rzeczy
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/uchwala_rady_21_02_2019.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Warunki-rejestracji-na-kolejny-semestr-rok-studiow-22.11.2023.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Procedura-przeprowadzania-sprawdzian%C3%B3w.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/katalog-obieralne-2023.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Poradnik-Stypendialny-SSPW-2025-2026.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Informacje-bhp-WMiNI.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Plan-studiow-I-st-MAD.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Plan-studiow-I-st-Mat-1.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Plan-studiow-I-st-ISI.pdf",
    # POBIERZ RĘCZNIE PDF (BIP PW — cookiewall): "https://bip.pw.edu.pl/var/pw/storage/original/application/6ae70089d460bc9ba71566298fa79fcf.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Plan-studiow-I-st-CSIS.pdf",
    # POBIERZ RĘCZNIE PDF (BIP PW — cookiewall): "https://bip.pw.edu.pl/var/pw/storage/original/application/5e62794f9cf903f4ef2e16869f704020.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/20250529-iad-plan-studiow-inz.pdf",
    # POBIERZ RĘCZNIE PDF (BIP PW — cookiewall): "https://bip.pw.edu.pl/var/pw/storage/original/application/09dde30f2523fec5088b62dbdd727a73.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/regulamin_praktyk_14_04_2022.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/praktyki_prezentacja_2025.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Plan-studiow-II-st-MAD.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/f676afa0d765aa67153d0b03ff3026d9.pdf",
    "https://ww2.mini.pw.edu.pl/studia/magisterskie/matematyka-i-analiza-danych/probabilistyka-i-modelowanie/",
    "https://ww2.mini.pw.edu.pl/studia/magisterskie/matematyka-i-analiza-danych/statystyka-matematyczna-i-analiza-danych/",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Plan-studiow-II-st-Mat.pdf",
    # POBIERZ RĘCZNIE PDF (BIP PW — cookiewall): "https://bip.pw.edu.pl/var/pw/storage/original/application/df978333880183b4bc4906362e74a2f8.pdf",
    "https://ww2.mini.pw.edu.pl/studia/magisterskie/matematyka/indywidualne-studia-matematyczne/",
    "https://ww2.mini.pw.edu.pl/studia/magisterskie/matematyka/mni/",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Plan-studiow-II-st-ISI-MSI.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Plan-studiow-II-st-ISI-CC.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Regulamin-zamowien-scalone.pdf",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/parking_zasady_2013_05_20.pdf",
    "https://ww2.mini.pw.edu.pl/laboratorium/uslugi/usluga-id/",
    "https://ww2.mini.pw.edu.pl/laboratorium/uslugi/usluga-wirtualki/",
    
    # Ważne newsy
    "https://ww2.mini.pw.edu.pl/2018-04-23-wydzial-matematyki-i-nauk-informacyjnych-podpisalo-porozumie-o-wspolpracy-z-ministerstwem-finansow/",
    "https://ww2.mini.pw.edu.pl/miedzynarodowa-rozpoznawalnosc-absolwentow-wydzialu/",
    "https://ww2.mini.pw.edu.pl/srodki-unii-europejskiej-dla-kierunku-data-science/",
    "https://ww2.mini.pw.edu.pl/prestizowa-nagroda-ptm/",
    "https://ww2.mini.pw.edu.pl/program-miedzynarodowej-certyfikacji-sas-data-science-dla-studentow-wydzialu/",
    "https://ww2.mini.pw.edu.pl/opinia-pracodawcow-o-kierunku-matematyka-i-analiza-danych/",
    "https://ww2.mini.pw.edu.pl/najwyzsze-zarobki-wsrod-absolwentow-kierunku-matematyka-osiagaja-wedlug-https-ela-nauka-gov-pl-absolwenci-politechniki-warszawskiej/",
    "https://ww2.mini.pw.edu.pl/mini-elitarne-kierunki-dla-najlepszych/",
    "https://ww2.mini.pw.edu.pl/wysokie-zarobki-absolwentow-mini-pw/",
    "https://ww2.mini.pw.edu.pl/wysokie-zarobki-absolwentow-mini-pw-z-roku-2022/",
    "https://ww2.mini.pw.edu.pl/studia-na-mini-zajely-pierwsze-i-drugie-miejsce-w-rankingu-perspektyw-2025/",
    "https://ww2.mini.pw.edu.pl/wysokie-zarobki-absolwentow-mini-pw-z-roku-2023-matematyka-10-441-i-miejsce-w-polsce/",
    "https://ww2.mini.pw.edu.pl/czternastu-pracownikow-wydzialu-mini-nagrodzonych-w-plebiscycie-zlotej-kredy/",
    "https://ww2.mini.pw.edu.pl/prof-dr-hab-grzegorz-swiatek-wybrany-do-rady-doskonalosci-naukowej/",
    "https://ww2.mini.pw.edu.pl/matematyka-i-analiza-danych-na-drugim-miejscu-w-polsce/",
    "https://ww2.mini.pw.edu.pl/indywidualne-studia-dla-najlepszych-kandydatow-i-studentow/",
    "https://ww2.mini.pw.edu.pl/studia-na-mini-zajely-pierwsze-i-drugie-miejsce-w-rankingu-perspektyw/",
    "https://ww2.mini.pw.edu.pl/zeszyt-online-platforma-z-zadaniami-matematycznymi-stworzona-i-rozwijana-przez-zespol-z-mini-pw/",
    "https://ww2.mini.pw.edu.pl/nowe-wladze-ptm/",
    "https://ww2.mini.pw.edu.pl/certyfikat-enaee-dla-kierunku-informatyka-i-systemy-informacyjne-na-wydziale-mini-pw-na-studiach-i-go-i-ii-ego-stopnia/",
    "https://ww2.mini.pw.edu.pl/odznaczenia/",
    "https://ww2.mini.pw.edu.pl/nagroda-dla-prof-wesolowskiego/",
    "https://ww2.mini.pw.edu.pl/odznaczenia-2/",
    "https://ww2.mini.pw.edu.pl/nominacje-profesorskie/",
    "https://ww2.mini.pw.edu.pl/odznaczenia-3/",
    "https://ww2.mini.pw.edu.pl/test-2/",
    "https://ww2.mini.pw.edu.pl/wysokie-wynagrodzenia-absolwentow-matematyki-naszego-wydzialu/",
    "https://ww2.mini.pw.edu.pl/kierunek-inzynieria-i-analiza-danych-bije-rekordy-popularnosci/",
    "https://ww2.mini.pw.edu.pl/przyznane-granty-dla-pracownikow-wydzialu-mini/",
    "https://ww2.mini.pw.edu.pl/ocena-wyrozniajaca-polskiej-komisji-akredytacyjnej-dla-kierunku-matematyka/",
    "https://ww2.mini.pw.edu.pl/jubileuszowy-rok-matematyki/",
    "https://ww2.mini.pw.edu.pl/wydzial-mini-ustanowil-nowy-rekord-polski/",
    "https://ww2.mini.pw.edu.pl/studentka-naszego-wydzialu-laureatka-stypendium-intel-perspektywy/",
    "https://ww2.mini.pw.edu.pl/student-naszego-wydzialu-laureatem-programu-stypendium-pod-choinke/",
    "https://ww2.mini.pw.edu.pl/seminaria-data-science-news/",
    "https://ww2.mini.pw.edu.pl/11770-2/",
    "https://ww2.mini.pw.edu.pl/14-marca-miedzynarodowy-dzien-matematyki/",
    "https://ww2.mini.pw.edu.pl/ogolnopolski-konkurs-na-najlepsza-prace-magisterska-dotyczaca-uczenia-maszynowego-lub-analizy-danych/",
    "https://ww2.mini.pw.edu.pl/wp-content/uploads/Ogloszenie-homo-1.pdf",
    "https://ww2.mini.pw.edu.pl/obrona-rozprawy-doktorskiej-mgr-urszuli-pastwy/",
    "https://ww2.mini.pw.edu.pl/kolejny-etap-rekrutacji-do-projektu-szkola-orlow-na-pw/",
    "https://ww2.mini.pw.edu.pl/informacje-dotyczace-funkcjonowania-uczelni-oraz-regulamin-przebywania-w-gmachu-wydzialu-mini-w-czasie-epidemii/",
    "https://ww2.mini.pw.edu.pl/szlachetna-paczka-na-pw/",
    "https://ww2.mini.pw.edu.pl/matematyka-w-cyberbezpieczenstwie-nowa-specjalnosc-na-studiach-ii-stopnia/",
    "https://ww2.mini.pw.edu.pl/nagroda-ministra-edukacji-i-nauki-za-uruchomienie-kierunku-data-science-na-wydziale-mini/",
    "https://ww2.mini.pw.edu.pl/mini-pw-solidarne-z-ukraina/",
    "https://ww2.mini.pw.edu.pl/i-miejsce-informatyki-na-mini-w-rankingu-kierunkow-studiow-inzynierskich-perspektywy-2022/",
    "https://ww2.mini.pw.edu.pl/kiermasz-swiateczny-pw-5-6-grudnia-2024/",
    "https://ww2.mini.pw.edu.pl/7-maja-w-gmachu-mini-odbylo-sie-spotkanie-ze-stefanem-batorym/",
    "https://ww2.mini.pw.edu.pl/publiczne-kolokwium-habilitacyjne-dra-adama-kubicy/",
    "https://ww2.mini.pw.edu.pl/matematyka-oraz-informatyka-ponownie-na-drugim-miejscu-w-polsce-w-rankingu-qs-by-subject-wg-dyscyplin-akademickich/",
    "https://ww2.mini.pw.edu.pl/sukces-absolwentow-mini-w-konkursie-ptm-na-najlepsza-prace-z-teorii-prawdopodobienstwa-i-zastosowan-matematyki/",
    "https://ww2.mini.pw.edu.pl/prezydent-rp-nadal-tytul-profesora-dr-hab-michalowi-ziembowskiemu/",
    "https://ww2.mini.pw.edu.pl/zespol-combains-z-sukcesem-w-hackcarpathia-2026/",
    "https://ww2.mini.pw.edu.pl/sukces-druzyn-z-mini-w-hackatonie-starkhacks-w-usa/",
    
    # Socials
    # "https://www.facebook.com/wrsminipw",
    # "https://www.facebook.com/samorzadpw",

    # obieraki
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/szukajPrzedmiotu&method=faculty_groups&jed_org_kod=112000&grupaKod=1120-OBIERALNE&callback=g_181b84c2&cp_showDescriptions=0&cp_showGroupsColumn=0&cp_cdydsDisplayLevel=2&f_tylkoWRejestracji=0&f_obcojezyczne=0&kierujNaPlanyGrupy=0&tab5585_offset=0&tab5585_limit=300&tab5585_order=2a1a",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-ISA-0548&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0548&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0547&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0507&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-ISP-0693&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0508&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-MSA-0500&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-MSP-0566&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0619&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-ISA-0568&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0684&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1030-IN000-ISA-0572&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-ISP-0518&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0627&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-ISP-0519&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1030-IN000-ISP-0578&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0524&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0686&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0692&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-INCAD-MSP-0583&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1050-IN000-ISA-0584&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-ISP-0592&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-ISA-0503&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1030-IN000-ISP-0595&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-ISP-0698&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-ISP-0606&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-NSP-0601&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0541&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1170-IN000-MSP-0662&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-DS000-ISP-0235&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0537&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0537&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-IN000-ISA-0508&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-MA000-LSP-0648&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-DS000-ISP-0236&callback=g_1bb9ff53",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-INCAD-MSP-0500&callback=g_1bb9ff53",
    
    # ── BIP PW ───────────────────────────────────────────────────────────────
    # Strony i pliki BIP PW wymagają ręcznego pobrania (cookiewall / JS rendering).
    # PDF-y wrzuć do src/manual_pdfs/ i uruchom workflow "Ingest Only".
    # Strony HTML na razie pominięte — nie da się ich automatycznie zescrapować.
    # ─────────────────────────────────────────────────────────────────────────

    # PDF files (pobierz ręcznie):
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/application/d306a4288f0943c31b5e9cd8fcd33f73.pdf",
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/application/a7f6351019e1d70a951c7a1ac1bb0e28.pdf",
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/application/62f1b26a2cee774b5699342e29970bbf.pdf",
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/application/bc54edfe5cc419713f931181db92ef46.pdf",
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/application/a3de1af7fada945beb87a825dbb0c262.pdf",
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/application/b316729d09938e94c7eb5528b0e0744d.pdf",
    # "https://bip.pw.edu.pl/var/pw/storage/original/application/7fe181576ef6f818438bc0b3df98e13f.pdf",
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/application/84cf2faf2873685ac94833c869fe866f.pdf",
    # "https://bip.pw.edu.pl/var/pw/storage/original/application/35ef86bbcf1cd086fee4fd97f088aa47.pdf",
    # "https://bip.pw.edu.pl/var/pw/storage/original/application/c82085781d743edb519bd365df87aded.pdf",
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/application/ee0f54fc508ca6edb94560f70b4dcd8b.pdf",
    # "https://bip.pw.edu.pl/var/pw/storage/original/application/390bf595ba50c2b63d98e7056c54b61f.pdf",
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/application/2b1c27e1c5245605dfdf71342a8b11b9.pdf",
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/application/e047e0025a88927817f200f6ef12d364.pdf",
    # "https://www.bip.pw.edu.pl/var/pw/storage/original/text/5c2f61cbc7cc5ab7defe27a20a2f1729.xml",
    
    # HTML pages (cookiewall — niedostępne dla scrapera):
    # "https://www.bip.pw.edu.pl/Sklad-osobowy/Podstawowe-jednostki-organizacyjne/Wydzial-Matematyki-i-Nauk-Informacyjnych",
    # "https://www.bip.pw.edu.pl/Wladze/Senat",
    # "https://www.bip.pw.edu.pl/Wladze/Rady-Naukowe-Dyscyplin/Rada-Naukowa-Dyscypliny-Matematyka-Politechniki-Warszawskiej",
    # "https://www.bip.pw.edu.pl/content/view/full/18994",
    # "https://www.bip.pw.edu.pl/index.php/content/view/full/38019",
    # "https://www.bip.pw.edu.pl/Dokumenty-publiczne/Legitymacja-studencka-w-Politechnice-Warszawskiej",
    # "https://www.bip.pw.edu.pl/Dokumenty-publiczne/Dyplom-ukonczenia-studiow-w-Politechnice-Warszawskiej",
    # "https://www.bip.pw.edu.pl/content/view/full/314",
    # "https://www.bip.pw.edu.pl/index.php/Sprawy-Studenckie/Regulamin-studiow-w-Politechnice-Warszawskiej2",
    # "https://www.bip.pw.edu.pl/index.php/Terminarze-posiedzen-i-sklady-Rad-Wydzialow/Wydzial-Matematyki-i-Nauk-Informacyjnych",
    # "https://www.bip.pw.edu.pl/index.php/content/view/full/358",
    # "https://www.bip.pw.edu.pl/Wewnetrzne-akty-prawne/Dokumenty-Senatu-PW/Uchwaly-Senatu-PW/2024-L/Uchwala-nr-484-L-2024-Senatu-Politechniki-Warszawskiej-z-dnia-29-maja-2024-r",
    # "https://www.bip.pw.edu.pl/content/view/full/304",
    # "https://www.bip.pw.edu.pl/Wladze/Rada-Uczelni",
    # "https://www.bip.pw.edu.pl/Wladze/Prorektorzy/Prorektor-ds.-Ogolnych",
    # "https://www.bip.pw.edu.pl/Wladze/Prorektorzy/Prorektor-ds.-Nauki",
    # "https://www.bip.pw.edu.pl/Wladze/Prorektorzy/Prorektor-ds.-Studiow",
    # "https://www.bip.pw.edu.pl/Wladze/Prorektorzy/Prorektor-ds.-Rozwoju",
    # "https://www.bip.pw.edu.pl/Wladze/Prorektorzy/Prorektor-ds.-Studenckich",
    # "https://www.bip.pw.edu.pl/Wladze/Prorektorzy/Prorektor-ds.-Filii-w-Plocku",
    # "https://www.bip.pw.edu.pl/Sklad-osobowy/Organizacje-spoleczne/Samorzad-Studentow",
    # "https://www.bip.pw.edu.pl/index.php/Udzielanie-informacji-publicznej/Sposob-uzyskania-informacji",
    # "https://www.bip.pw.edu.pl/index.php/Sprawy-Studenckie/Praca-dla-studentow",
    # "https://www.bip.pw.edu.pl/Praca-w-Politechnice/Dla-nie-nauczycieli",
    # "https://www.bip.pw.edu.pl/content/view/full/72145",
    # "https://www.bip.pw.edu.pl/Wladze/Kanclerz-Zastepcy-Kanclerza/Kanclerz",
    # "https://www.bip.pw.edu.pl/content/view/full/46644",
    # "https://www.bip.pw.edu.pl/index.php/Dokumentacja-kontroli-i-raporty/Raporty-i-uchwaly-Polskiej-Komisji-Akredytacyjnej",
    # "https://www.bip.pw.edu.pl/index.php/content/view/full/19245",
    # "https://www.bip.pw.edu.pl/index.php/Wybory/Uczelniana-Komisja-Wyborcza/Wyniki-Wyborow-na-kadencje-2024-2028",
    # "https://www.bip.pw.edu.pl/index.php/content/view/full/65915",
    # "https://www.bip.pw.edu.pl/index.php/content/view/full/65916",
    # "https://www.bip.pw.edu.pl/index.php/content/view/full/65917",

    # plany zajęć
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISA-S1&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISA-S3&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISA-S5&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISA-S7&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-ELECTIVES-2025Z&cdyd_kod=2025Z&plan_showSettings=1&2plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=0&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISP-S1&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISP-S3&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISP-S5&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISP-S7&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIMSI-S1Z3-Z&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIMSI-S2Z3-L&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIMSI-S3Z3-L&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-OBIERALNE-2025Z&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MALSP-S1&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MALSP-S3&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MALSP-S5&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MANSP-MCB-1N&cdyd_kod=2025Z",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MANSP-MCB-3P&cdyd_kod=2025Z",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-OBIERALNE-2025Z&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDLSP-S1&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDLSP-S3&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDLSP-S5&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDNSP-PRIMO-1&cdyd_kod=2025Z",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDNSP-PRIMO-3&cdyd_kod=2025Z",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDNSP-SMAD-1&cdyd_kod=2025Z",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDNSP-SMAD-3&cdyd_kod=2025Z",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-OBIERALNE-2025Z&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSISP-S1&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSISP-S3&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSISP-S5&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSISP-S7&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-OBIERALNE-2025Z&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSMSA-S1Z4&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSMSA-S2Z3&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSMSA-S3Z4&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-ELECTIVES-2025Z&cdyd_kod=2025Z&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=0&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-OBIERALNE-2026L&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDNSP-SMAD-4&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISA-S2&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISA-S4&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISA-S6&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-ELECTIVES-2026L&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISP-S2&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISP-S4&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIISP-S6&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIMSI-S1Z3-L&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIMSI-S2Z3-Z&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSIMSI-S3Z3-L&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSICAD-S1Z3-L&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSICAD-S2Z3-Z&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-INSICAD-S3Z3-ZL&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-OBIERALNE-2026L&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSISP-S2&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSISP-S4&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSISP-S6&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-OBIERALNE-2026L&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSMSA-S1Z3&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSMSA-S2Z4&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSMSA-S3Z3&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-DSMSA-S4Z4&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-ELECTIVES-2026L&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MALSP-S2&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MALSP-S4&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MALSP-S6&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MANSP-MCB-2N&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MANSP-MCB-4P&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-OBIERALNE-2026L&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDLSP-S2&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDLSP-S4&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDLSP-S6&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDNSP-PRIMO-2&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDNSP-PRIMO-4&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",
    "https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPlanGrupyPrzedmiotow&grupa_kod=1120-MDNSP-SMAD-2&cdyd_kod=2026L&plan_showSettings=1&plan_showStartTime=1&plan_showEndTime=1&plan_showTypeShort=1&plan_showTypeFull=0&plan_showGroupNumber=1&plan_showCourseName=1&plan_showCourseCode=0&plan_showRoom=1&plan_showBuildingCode=1&plan_showLecturers=1&plan_overridePrintWidth=1&plan_format=html&plan_colorScheme=default",

    # Pracownicy MiNI
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_ayoush_rami/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_balicki_jerzy/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_banecki_krzysztof/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_bednarczuk_ewa/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_biecek_przemyslaw/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_bies_piotr/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_blaszczyk_lukasz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_bobecka-wesolowska_konstancja/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_cena_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_chelminski_krzysztof/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_cieslak_tomasz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_dabrowski-tumanski_pawel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_dembinska_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_denkiewicz_michal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_debski_michal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_domitrz_wojciech/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_gaczkowski_michal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_ganzha_maria/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_gagolewski_marek/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_gorka_przemyslaw/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_grytczuk_jaroslaw/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_grzegorzewski_przemyslaw/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_grzenda_maciej/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_henriques_dos_santos_de_sepulveda_nuno/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_herman_tomasz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_homenda_wladyslaw/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_jaksztas_ludwik/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_janeczko_stanislaw/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_jaroszewicz_szymon/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_jasionowska-skop_magdalena/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_jastrzebska_agnieszka/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_jelowicki_franciszek/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_joziak_pawel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_junosza-szaniawski_konstanty/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kaczmarski_krzysztof/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_karpinska_boguslawa/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kazmierczak_stanislaw/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kolodziejczyk_danuta/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kolodziejek_bartosz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_korsak_sevastianos/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kotus_janina/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kozak_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kozlowska_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_krawczyk_tomasz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_przelaskowski_artur/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_pytlak_radoslaw/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_rutkowski_marek/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_ryszewska_katarzyna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_rzazewski_pawel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_sawicki_jan/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_sengupta_kaustav/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_porter-sobieraj_joanna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kubica_adam/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_lonc_zbigniew/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_luckner_marcin/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_lyczak_marcin/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_mandziuk_jacek/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_mielniczuk_jan/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_nieweglowski_mariusz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_okrasa_karolina/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_owczarek_sebastian/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_paczka_dariusz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_pilitowska_agata/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_plewczynski_dariusz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_plocharski_aleksander/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_sienkiewicz_elzbieta/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_slabuszewski_artur/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_stronkowski_michal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_syga_monika/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_szpojankowski_kamil/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_sleszynska-nowak_malgorzata/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_swiatek_grzegorz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_swieca_marcin/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_teisseyre_pawel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_tur_szymon/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_wesolowski_jacek/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_wlasnowolski_michal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_woznica_katarzyna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_wroblewska_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_zamojska-dzienio_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_ziembowski_michal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_zwierzynski_michal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_zygula_szymon/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_zychowski_adam/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_konecka_elena/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kostrzewa_tomasz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kotowski_pawel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kozlowski_marek/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_krasnosielska-kobos_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_abelski_jakub/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_aszklar_pawel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_bartczak_leszek/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_binczak_grzegorz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_bogdewicz_agnieszka/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_boratynski_wojciech/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_brengos_tomasz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_brodka_jan/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_brzozowski_lukasz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_buba-brzozowa_malgorzata/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_chmielewska_joanna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_chojecki_adam/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_danielak_katarzyna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_figurny_piotr/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_frankiewicz_ewa/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_galazka_piotr/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_gorak_rafal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_gruszka_renata/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_herburt_irmina/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_jozwiak_rafal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_junosza-szaniawska_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_keller_pawel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kisiel_konrad/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_komorowski_adam/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_pilarski_marcin/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_piliszek_agnieszka/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_przyborowska_marta/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_radzikowska_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_rafalko_janusz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_renska_miroslawa/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_roszkowska-lech_barbara/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_rudas_krzysztof/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_ruzikowska_agnieszka/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_rydzewska_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_samsonowicz_jan/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_sidz_leszek/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_sobczyk_jaroslaw/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_sobotka_pawel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_socha_dariusz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_sojka_grzegorz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_spalinski_jan/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_spychala_maciej/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_stepien_katarzyna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_krasuski_krzysztof/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_lesniewski_andrzej/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_lesniewski_krzysztof/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_lewinska_ewa/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_macukow_bohdan/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_maj_rafal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_malysz_robert/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_matysiak_joanna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_matysiak_wojciech/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_mucka_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_naroski_pawel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_opolska-rutkowska_malgorzata/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_ostrek_grzegorz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_pietrzkowski_gabriel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_stepnicki_robert/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_strozyna_ewa/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_slusarska_karolina/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_tarka_joanna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_trebska_zaneta/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_tuczynski_michal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_walczynska_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_wojcicki_pawel/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_wrobel_iwona/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_zadrzynska-pietka_ewa/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_zajac_mariusz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_zapart_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_zimnicka_agnieszka/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_anucinska_agnieszka/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_baranowska_monika/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_baranska_anna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_berlak_joanna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_bogucka_magdalena/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_borkowski_marcin/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_broniarek_jakub/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_burchart_dagmara/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_gostomska-kosiorek_monika/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kadlof_michal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_kmita_katarzyna/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_olobry_magdalena/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_pajak_hubert/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_radzki_michal/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_rogowski_grzegorz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_sikorska_malgorzata/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_skonecka_agnieszka/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_sofka_elzbieta/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_szczesna_ewelina/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_traczyk_tomasz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_swiderek_adrian/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_traczyk_tomasz/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_zielinska_agnieszka/",
    "https://ww2.mini.pw.edu.pl/wydzial/pracownicy/prac_zuk_agnieszka/"
]
