name: Deploy Chatbot MiNI

on:
  push:
    branches: [ new_pipeline ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Start Frontend only
          run: docker compose up -d --build
