name: Deploy Chatbot MiNI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy .env file
        run: cp ~/.env.backup .env
      - name: Stop old containers
        run: docker compose down
      - name: Build image
        run: docker compose build --no-cache
      - name: Start application
        run: docker compose up -d
      - name: Clean up dangling images and build cache
        run: docker system prune -f
